name       : libfann
version    : 2.2.0
release    : 1
source     :
    - https://github.com/libfann/fann/archive/2.2.0.tar.gz : f31c92c1589996f97d855939b37293478ac03d24b4e1c08ff21e0bd093449c3c
license    : LGPL-2.1-only
component  : programming.library
summary    : Fast Artificial Neural Network (FANN) Library
description: |
    Fast Artificial Neural Network Library is a free open source neural network library, which implements multilayer artificial neural networks in C with support for both fully connected and sparsely connected networks.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install